octopus:
  environments:
    - development
    - production
  development:
    shard_one:
      adapter: postgresql
      database: crawler_development
      pool: 100
  production:
    shard_one:
      host: ec2-107-20-254-2.compute-1.amazonaws.com
      adapter: postgresql
      database: d1jtd30fmmju80
      port: 5562
      username: u78dtp9gsq4msu
      password: per2pkece93kvd7ir8889t7p8gr
      pool: 100