octopus:
  environments:
    - development
    - production
  development:
    development_shard:
      adapter: postgresql
      database: crawler_development
      pool: 25
  production:
    master:
      adapter: postgresql
      <%= "database: #{ENV["MAIN_DB_NAME"]}" %>
      <%= "username: #{ENV["MAIN_DB_USER"]}" %>
      <%= "password: #{ENV["MAIN_DB_PASS"]}" %>
      <%= "host: #{ENV["MAIN_DB_HOST"]}" %>
      <%= "port: #{ENV["MAIN_DB_PORT"]}" %>
      pool: 25
    production_shard:
      <%= "adapter: postgresql" %>
      <%= "database: #{ENV["DB_NAME"]}" %>
      <%= "username: #{ENV["DB_USER"]}" %>
      <%= "password: #{ENV["DB_PASS"]}" %>
      <%= "host: #{ENV["DB_HOST"]}" %>
      <%= "port: #{ENV["DB_PORT"]}" %>
      pool: 25