octopus:
  environments:
    - development
    - production
  development:
    main_shard:
      adapter: postgresql
      database: crawler_development
      pool: 3
      reaping_frequency: 3
    master:
      adapter: postgresql
      database: crawler_development
      pool: 80
      reaping_frequency: 3
  production:
    <% if ENV["DB_NAME"].present? %>
    master:
      <%= "adapter: postgresql" %>
      <%= "database: #{ENV["DB_NAME"]}" %>
      <%= "username: #{ENV["DB_USER"]}" %>
      <%= "password: #{ENV["DB_PASS"]}" %>
      <%= "host: #{ENV["DB_HOST"]}" %>
      <%= "port: #{ENV["DB_PORT"]}" %>
      pool: 80
      reaping_frequency: 3
    <% end %>
    main_shard:
      adapter: postgresql
      database: daji1hvabgdc0c
      username: ue9r4mdvjgsktq
      password: p9rem1q40biu605siarnkvp2i83
      host: ec2-184-73-202-38.compute-1.amazonaws.com
      port: 5532
      pool: 1
      reaping_frequency: 3