octopus:
  environments:
    - development
    - production
  development:
    main_shard:
      adapter: postgresql
      database: crawler_development
      pool: 3
    master:
      adapter: postgresql
      database: crawler_development
      pool: 25
    processor:
      adapter: postgresql
      database: crawler_development
      pool: 25
  production:
    <% if ENV["DB_NAME"].present? %>
    master:
      <%= "adapter: postgresql" %>
      <%= "database: #{ENV["DB_NAME"]}" %>
      <%= "username: #{ENV["DB_USER"]}" %>
      <%= "password: #{ENV["DB_PASS"]}" %>
      <%= "host: #{ENV["DB_HOST"]}" %>
      <%= "port: #{ENV["DB_PORT"]}" %>
      pool: 25
    <% end %>
    main_shard:
      adapter: postgresql
      database: d43keikloc7ejh
      username: uda0tbtpqg53lu
      password: pfulh5el80spt6ehv206vs9qs1u
      host: ec2-54-163-235-96.compute-1.amazonaws.com
      port: 5482
      pool: 25
    processor:
      adapter: postgresql
      database: d570jqv21u9in0
      username: u5fkjshgbhhncg
      password: p843pa73aoj8sm9sb4pj4ol72vo
      host: ec2-54-163-234-153.compute-1.amazonaws.com
      port: 5432
      pool: 25